builders:
  eco:
    import: "package:eco/builders.dart"
    builder_factories:
      - "viewBuilder"
    build_extensions:
      .view.eco:
        - .html
    auto_apply: dependents
    applies_builders:
      - "|eco_clean_up"
post_process_builders:
  eco_clean_up:
    import: "package:eco/builders.dart"
    builder_factory: "cleanUpBuilder"
    input_extensions:
      - .eco