name: eco

publish_to: none

environment:
  sdk: '>=2.5.0 <3.0.0'

executables:
  eco:
  eco_view:

dependencies:
  build: ^1.0.0
  charcode: ^1.1.2
  meta: ^1.1.6
  path: ^1.6.2
  source_span: ^1.4.1
  string_scanner: ^1.0.4

dev_dependencies:
  test: ^1.3.4
